name: Build void packages

on:
  push:
    tags:
      - "*"

jobs:
  build:
    strategy:
      max-parallel: 1
      matrix:
        arch: [x86_64]
        # arch: [x86_64, x86_64-musl]
    runs-on: ubuntu-latest
    env:
      XBPS_PASSPHRASE: ${{ secrets.SIGN_PASS }}
      XBPS_TARGET_ARCH: ${{ matrix.arch }}
      REPO_OWNER: "${{ github.repository_owner }}"
      REPO_NAME: "${{ github.event.repository.name }}"

    steps:
      - name: checkout ${{ env.REPO_NAME }}
        uses: actions/checkout@v4
        with:
          ref: main
          path: ${{ env.REPO_NAME }}

      - name: checkout void-packages
        uses: actions/checkout@v4
        with:
          repository: void-linux/void-packages
          ref: master
          path: void-packages

      - name: copy
        run: cp -rv ${{ env.REPO_NAME }}/srcpkgs/* void-packages/srcpkgs

      - name: prepare xbps-static
        run: |
          mkdir -p /opt/xbps
          curl -LO http://repo-default.voidlinux.org/static/xbps-static-latest.x86_64-musl.tar.xz
          tar xvf xbps-static-latest.x86_64-musl.tar.xz -C /opt/xbps
          rm xbps-static-latest.x86_64-musl.tar.xz

      # - name: free space
      #   run: |
      #     sudo rm -rf /usr/share/dotnet
      #     sudo rm -rf /usr/local/lib/android
      #     sudo rm -rf /opt/ghc
      #     sudo rm -rf /opt/hostedtoolcache/CodeQL

      - name: set path
        run: |
          echo "/opt/xbps/usr/bin/" >> $GITHUB_PATH

      - name: setup binray bootstrap
        working-directory: void-packages
        run: |
          ./xbps-src -m masterdir-${{ matrix.arch }} -A ${{ matrix.arch }} binary-bootstrap

      - name: build chrome
        working-directory: void-packages
        run: |
          sed -i '/^repository=nonfree/d' srcpkgs/google-chrome/template
          ./xbps-src pkg -j4 -m masterdir-${{ matrix.arch }} google-chrome

      - name: sign
        working-directory: void-packages/hostdir/binpkgs/
        run: |
          xbps-rindex -r $PWD
          xbps-rindex -s --signedby "${{ env.REPO_NAME }}-github-action" --privkey <(printf '%s' "${{ secrets.PRIV_KEY }}") $PWD
          xbps-rindex -S --privkey <(printf '%s' "${{ secrets.PRIV_KEY }}") $PWD/*.xbps
          xbps-rindex -c $PWD

      # - name: checksum
      #   working-directory: void-packages/hostdir/binpkgs/
      #   run: |
      #     sha256sum $(echo librewolf-*.${{ matrix.arch }}.xbps) | tee $(echo librewolf-*.${{ matrix.arch }}.xbps).sha256sum
      #     sha512sum $(echo librewolf-*.${{ matrix.arch }}.xbps) | tee $(echo librewolf-*.${{ matrix.arch }}.xbps).sha512sum

      - name: release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            void-packages/hostdir/binpkgs/*.xbps
            void-packages/hostdir/binpkgs/*repodata
